[package]
name = "rf-comp-dsp"
description = "The feed-forward stereo compressor of RF-Comp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rf-comp-contract.workspace = true
libm = { workspace = true }

[dev-dependencies]
rf-comp-contract.workspace = true
